name: Deploy MuleSoft Application
 
on:
  push:
    branches:
      - demo
  pull_request:
    branches:
      - demo


jobs:
  call-workflow:
    uses: gowrisankarvaka/algolia-api/.github/workflows/reusableWorkflow.yml@demo
    secrets: inherit
